# Generated by Django 2.2 on 2019-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('fastafile', models.FileField(upload_to='scpc/recordsfile/')),
                ('newickfile', models.FileField(upload_to='scpc/recordsfile/')),
                ('access_code', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('resultfile', models.FileField(default='K80', upload_to='')),
            ],
        ),
    ]
